[project]
name = "eigenfluids-3d"
version = "0.1.0"
description = "A 3D Implementation of Fluid Simulation Using Laplacian Eigenfunctions in JAX"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jax>=0.4.30",
    "polyscope>=2.5.0",
]
